// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_localisation/test/translator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_localisation/src/service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/shared_preferences.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TranslationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTranslationService extends _i1.Mock
    implements _i2.TranslationService {
  MockTranslationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isReady => (super.noSuchMethod(
        Invocation.getter(#isReady),
        returnValue: false,
      ) as bool);

  @override
  bool get isApiConfigured => (super.noSuchMethod(
        Invocation.getter(#isApiConfigured),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoggingEnabled => (super.noSuchMethod(
        Invocation.getter(#isLoggingEnabled),
        returnValue: false,
      ) as bool);

  @override
  set prefs(_i3.SharedPreferences? _prefs) => super.noSuchMethod(
        Invocation.setter(
          #prefs,
          _prefs,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> initialize({bool? fetchUpdatesOnStart = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {#fetchUpdatesOnStart: fetchUpdatesOnStart},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String? getOverride(
    String? locale,
    String? key,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getOverride,
        [
          locale,
          key,
        ],
      )) as String?);

  @override
  bool hasOverride(
    String? locale,
    String? key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasOverride,
          [
            locale,
            key,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  Map<String, int> getCacheStatus() => (super.noSuchMethod(
        Invocation.method(
          #getCacheStatus,
          [],
        ),
        returnValue: <String, int>{},
      ) as Map<String, int>);

  @override
  _i4.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  Map<String, String> getAllOverridesForLocale(String? locale) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllOverridesForLocale,
          [locale],
        ),
        returnValue: <String, String>{},
      ) as Map<String, String>);
}
