// lib/saas_translations.dart
library saas_translations;

export 'src/config.dart';
// This file will be generated by the package
export 'src/provider.dart';
// Core exports
export 'src/service.dart';
