// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by FlutterLocalisation Translations package
// Generated on: 2025-11-10T15:52:37.072995

import 'package:flutter_localisation/flutter_localisation.dart';

/// Timestamp of embedded ARB files used during generation
const String embeddedArbTimestamp = '';

/// Generated extension methods for FlutterLocalisation translations
extension GeneratedTranslationMethods on Translator {

  /// Generated getter for appTitle
  String get appTitle {
    return translate(
      'appTitle',
      {},
      () => generatedLocalizations.appTitle,
    );
  }

  /// Generated method for hello
  String hello(Object name) {
    return translate(
      'hello',
      {'name': name},
      () => generatedLocalizations.hello(name),
    );
  }

  /// Generated method for welcomeMessage
  String welcomeMessage(Object username) {
    return translate(
      'welcomeMessage',
      {'username': username},
      () => generatedLocalizations.welcomeMessage(username),
    );
  }

  /// Generated getter for simpleGreeting
  String get simpleGreeting {
    return translate(
      'simpleGreeting',
      {},
      () => generatedLocalizations.simpleGreeting,
    );
  }

  /// Generated method for itemsInCart
  String itemsInCart(num count) {
    return translate(
      'itemsInCart',
      {'count': count},
      () => generatedLocalizations.itemsInCart(count),
    );
  }

  /// Generated getter for refresh
  String get refresh {
    return translate(
      'refresh',
      {},
      () => generatedLocalizations.refresh,
    );
  }
}
